[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[functions]
  node_bundler = "esbuild"
  included_files = ["supabase/functions/**/*"]
  external_node_modules = ["openai", "@supabase/supabase-js", "tweetnacl", "pdf-lib", "qrcode", "@simplewebauthn/server", "@octokit/rest"]

[[edge_functions]]
  path = "/api/*"
  function = "edge_guard"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co https://api.openai.com https://api.github.com; img-src 'self' data: blob:; script-src 'self'; style-src 'self' 'unsafe-inline'"