# Demo Bots GitHub Actions - Beta Terminal Testing
# FCA Compliant Aviation Platform - Proof of Life System

name: Demo Bots - Beta Terminal Testing

on:
  workflow_dispatch:
  schedule:
    # Run every 4 hours during business hours (London time)
    - cron: '17 */4 * * *'
    # Run every 6 hours from 9 AM to 9 PM (London time)
    - cron: '43 9-21/6 * * *'

jobs:
  run-bots:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          cd demo-bots/playwright
          npm init -y >/dev/null 2>&1 || true
          npm i -D @playwright/test
          npx playwright install --with-deps chromium
          
      - name: Run Broker Bot
        working-directory: demo-bots/playwright
        run: npx playwright test broker.spec.ts --reporter=list
        env:
          STRATUS_URL: ${{ secrets.STRATUS_URL }}
          SUPABASE_EVENTS_URL: ${{ secrets.SUPABASE_EVENTS_URL }}
        continue-on-error: true
        
      - name: Run Operator Bot
        working-directory: demo-bots/playwright
        run: npx playwright test operator.spec.ts --reporter=list
        env:
          STRATUS_URL: ${{ secrets.STRATUS_URL }}
          SUPABASE_EVENTS_URL: ${{ secrets.SUPABASE_EVENTS_URL }}
        continue-on-error: true
        
      - name: Run Pilot Bot
        working-directory: demo-bots/playwright
        run: npx playwright test pilot.spec.ts --reporter=list
        env:
          STRATUS_URL: ${{ secrets.STRATUS_URL }}
          SUPABASE_EVENTS_URL: ${{ secrets.SUPABASE_EVENTS_URL }}
        continue-on-error: true
        
      - name: Upload Playwright Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report-${{ github.run_number }}
          path: demo-bots/playwright/playwright-report
          retention-days: 30
          
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ github.run_number }}
          path: demo-bots/playwright/test-results
          retention-days: 30
